### ISSUE TITLE
uikit-sublime not working on sublime text 2

### ISSUE THREAD

**Issue by Iqlaas** [uikit/uikit-sublime#16]
Hello all.

As requested by @florianletsch ,

I followed exactly as it is in [(https://github.com/uikit/uikit-sublime)] but seems its not working as it should.

> When inside double quotes of a class attribute (class="[HERE]"), suggestions will appear for all uk- classes.

Quote above does not appear for me.

When I checked the sublime log,the below message appear

> Traceback (most recent call last):
File "./sublime_plugin.py", line 62, in reload_plugin
File "./main.py", line 3, in 
from .completions import classes, attributes
ValueError: Attempted relative import in non-package

My OS is OS X El Capitan Version 10.11.6 (15G1217)
Sublime Text 2.

**Comment by floriandotpy** [comment]
Okay, this looks like an import issue caused by the the different Python versions between Sublime Text 2 and 3. Is upgrading to Sublime Text 3 an option for you? That should fix the problem. I'd recommend using ST3 anyway, because ST2 has not seen any updates since 2013 and probably won't see any updates in the future.

**Comment by Iqlaas** [comment]
Yes, no problem. Hope this helps !

Awesome @florianletsch ! 👍

**Comment by floriandotpy** [comment]
Great!
