### ISSUE TITLE
uk-container-center

### ISSUE THREAD

**Issue by julianotheiss** [uikit/uikit-sublime#17]
I cant find class="uk-container-center" in the autocomplete.

**Comment by floriandotpy** [comment]
That class is no longer part of UIkit 3 (uk-container is centered by default). The sublime plugin has been updated to the UIkit 3 classes, which is why you won't find that class any more.

If you want to use the plugin for UIkit 2, you may downgrade manually: https://github.com/uikit/uikit-sublime/issues/15
